package pramedia.nmea;

/**
 *
 * @author Rampa Praditya
 */
public class Info extends javax.swing.JDialog {

    public Info(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // 1. Pastikan editor1 merender HTML dan tidak bisa diedit
        editor1.setContentType("text/html");
        editor1.setEditable(false);
        editor1.setText(htmlMessage); // htmlMessage adalah string HTML panjang sebelumnya

        // 2. Gulir otomatis scrollbar ke posisi paling atas saat dialog terbuka
        editor1.setCaretPosition(0);

        // 3. Tentukan ukuran proporsional jendela Info Anda (Lebar: 500px, Tinggi: 450px)
        this.setSize(550, 480);

        // 4. Pastikan jendela muncul tepat di tengah-tengah aplikasi utama (tidak di pojok layar)
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editor1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        editor1.setEditable(false);
        editor1.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(editor1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editor1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    String htmlMessage = "<html>"
            + "<body style='font-family: Arial, sans-serif; width: 450px; margin: 5px; color: #333333;'>"
            + "  <h3 style='margin-bottom: 2px; color: #2c3e50;'>1. GGA (Global Positioning System Fix Data)</h3>"
            + "  <p style='margin-top: 2px; font-size: 12px; color: #555555;'>"
            + "     Fokus utama GGA adalah memberikan informasi Akurasi, Ketinggian, dan Status Sinyal GPS."
            + "  </p>"
            + "  <b style='font-size: 11px; color: #888888;'>Contoh data Anda:</b>"
            + "  <div style='background-color: #f5f5f5; padding: 5px; font-family: monospace; font-size: 11px; border: 1px solid #ddd; margin: 3px 0 8px 0;'>"
            + "     $GPGGA,031850.412,0714.590,S,11246.139,E,1,11,1.0,0.0,M,,M,,*53"
            + "  </div>"
            + "  <b style='font-size: 11px; color: #888888;'>Artinya jika dibongkar:</b>"
            + "  <ul style='margin-top: 2px; padding-left: 20px; font-size: 12px;'>"
            + "     <li><b>031850.412</b> = Waktu UTC (03:18:50 lewat 412 milidetik)</li>"
            + "     <li><b>0714.590, S</b> = Latitude (Lintang Selatan)</li>"
            + "     <li><b>11246.139, E</b> = Longitude (Bujur Timur)</li>"
            + "     <li><b>1</b> = Fix Quality (0 = tidak ada sinyal, 1 = GPS fix standar, 2 = DGPS fix)</li>"
            + "     <li><b>11</b> = Jumlah Satelit yang terhubung (Ada 11 satelit)</li>"
            + "     <li><b>1.0</b> = HDOP (Akurasi horizontal, makin kecil makin akurat)</li>"
            + "     <li><b>0.0, M</b> = Ketinggian alat (0.0 Meter di atas permukaan laut)</li>"
            + "  </ul>"
            + "  <hr style='border:0; border-top: 1px solid #ddd; margin: 15px 0;'>"
            + "  <h3 style='margin-bottom: 2px; color: #2c3e50;'>2. RMC (Recommended Minimum Specific GPS Data)</h3>"
            + "  <p style='margin-top: 2px; font-size: 12px; color: #555555;'>"
            + "     Fokus utama RMC adalah memberikan <b>Data Esensial Navigasi</b> seperti Posisi, Kecepatan Bergerak, dan Tanggal."
            + "  </p>"
            + "  <b style='font-size: 11px; color: #888888;'>Contoh data Anda:</b>"
            + "  <div style='background-color: #f5f5f5; padding: 5px; font-family: monospace; font-size: 11px; border: 1px solid #ddd; margin: 3px 0 8px 0;'>"
            + "     $GPRMC,031850.412,A,0714.590,S,11246.139,E,8.1,112.0,090626,,,A*7E"
            + "  </div>"
            + "  <b style='font-size: 11px; color: #888888;'>Artinya jika dibongkar:</b>"
            + "  <ul style='margin-top: 2px; padding-left: 20px; font-size: 12px;'>"
            + "     <li><b>031850.412</b> = Waktu UTC</li>"
            + "     <li><b>A</b> = Status Validasi (A = Valid/Aktif, V = Void/Tidak Valid)</li>"
            + "     <li><b>0714.590, S & 11246.139, E</b> = Latitude & Longitude</li>"
            + "     <li><b>8.1</b> = Kecepatan (Speed over ground) dalam satuan Knots</li>"
            + "     <li><b>112.0</b> = Sudut arah gerak (Track angle) dalam derajat</li>"
            + "     <li><b>090626</b> = Tanggal hari ini (Format DDMMYY)</li>"
            + "  </ul>"
            + "</body>"
            + "</html>";
}
